@startuml name
actor User


User -> "Data By Region": clicks on button
"Data By Region" -> "Show Pie Chart": select chart type
"Show Pie Chart" -> "User choose region": select region
Frontend -> Redux : sends region name
Redux -> API : sends region name
API -> Redux : sends region data
Redux -> "Show Pie Chart" : sends region
"Show Pie Chart" -> "User": show chart

@enduml
